# Generated by Django 5.1.5 on 2025-01-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icons',
            field=models.FileField(null=True, upload_to='categories/'),
        ),
    ]
