# Generated by Django 5.1.5 on 2025-01-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_icons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icons',
            field=models.FileField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
