# Generated by Django 5.1.5 on 2025-01-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_slug_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pd', 'Pending'), ('pg', 'Processing'), ('shd', 'Shipped'), ('dd', 'Delivered'), ('cd', 'Cancelled')], max_length=3),
        ),
    ]
